Change 2 spaces to 4 spaces

diff --git a/www/varnish/files/varnish-vcl-reload.in b/www/varnish/files/varnish-vcl-reload.in
--- a/www/varnish/files/varnish-vcl-reload.in
+++ b/www/varnish/files/varnish-vcl-reload.in
@@ -2,14 +2,14 @@
 
 cfg=${1:-@PREFIX@/etc/varnish/default.vcl}
 if [ ! -e "$cfg" ]; then
-  printf 'ERROR: VCL file %s does not exist\n' "$cfg" >&2
-  exit 1
+    printf 'ERROR: VCL file %s does not exist\n' "$cfg" >&2
+    exit 1
 fi
 
 activecfg=$(varnishadm 'vcl.list' | awk '/active/ { print $3 }')
 if [ -z "$activecfg" ]; then
-  printf 'ERROR: No active VCL found!\n' >&2
-  exit 1
+    printf 'ERROR: No active VCL found!\n' >&2
+    exit 1
 fi
 
 newcfg=$(date +'vcl-%s')
